#pragma once
#define STD_MODE_NORMAL     0
#define STD_MODE_ALARM      1
#define STD_MODE_SECONDS    2
#define STD_MODE_COUNTDOWN  3
#define STD_MODE_DATE       4
#define STD_MODE_BRIGHTNESS 5
#define STD_MODE_BLANK      6
#define STD_MODE_COLORFUL   7
#define STD_MODE_COUNT      8
#define STD_MODE_NIGHT      9
#define EXT_MODE_START           10
#define EXT_MODE_MAIN_SETTINGS_START  10
#define EXT_MODE_LDR_MODE        11
#define EXT_MODE_CORNERS         12
#define EXT_MODE_ENABLE_ALARM    13
#define EXT_MODE_DCF_IS_INVERTED 14
#define EXT_MODE_LANGUAGE        15
#define EXT_MODE_TIME_SETTINGS_START  16
#define EXT_MODE_TIMESET         17
#define EXT_MODE_TIME_SHIFT      18
#define EXT_MODE_JUMP_TIMEOUT    19
#define EXT_MODE_OFFTIME_MOFR    20
#define EXT_MODE_ONTIME_MOFR     21
#define EXT_MODE_OFFTIME_SASO    22
#define EXT_MODE_ONTIME_SASO     23
#define EXT_MODE_TEST_DEBUG_START     24
#define EXT_MODE_TEST            25
#define EXT_MODE_DCF_SYNC        26
#define EXT_MODE_DCF_DEBUG       27
#define EXT_MODE_COUNT           28
